version: '3'

services: 
    
    web:
        image: node:12
        container_name: blocks-node
        tty: true
        volumes: 
            - ./:/apps/blocks-web
        working_dir: /apps/blocks-web
        networks: 
            - blocks-react-network

    webserver:
        image: nginx:1.20
        container_name: blocks-react-webserver
        tty: true
        volumes:
            - ./build:/usr/share/nginx/html
            - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "80:80"
        networks:
            - blocks-react-network

networks: 
    blocks-react-network: