name: Deploy to production.

on:
  push:
    branches: [master]

env:
  IMAGE_NAME: blocks-web
  IMAGE_NODE_NAME: blocks-web-node
  REGISTRY: repo.treescale.com/tfmblocks

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Building image
      run: |
        docker login ${{ env.REGISTRY }} --username ${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_PASSWORD }}
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest .
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NODE_NAME }}:latest -f Dockerfile.node .
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
